// Static demo reference data for Frostline Mechanical Services. All organisations and people are fictional.

export const USERS = [
  { key: 'martin', name: 'Martin Hale', email: 'martin.hale@frostline.co.uk', role: 'admin', job_title: 'Managing Director' },
  { key: 'susan', name: 'Susan Mercer', email: 'susan.mercer@frostline.co.uk', role: 'manager', job_title: 'Operations Director' },
  { key: 'rachel', name: 'Rachel Dunn', email: 'rachel.dunn@frostline.co.uk', role: 'coordinator', job_title: 'Service Coordinator' },
  { key: 'priya', name: 'Priya Shah', email: 'priya.shah@frostline.co.uk', role: 'coordinator', job_title: 'Service Coordinator' },
  { key: 'tom', name: 'Tom Barker', email: 'tom.barker@frostline.co.uk', role: 'coordinator', job_title: 'Service Desk Administrator' },
  { key: 'andy', name: 'Andy Cole', email: 'andy.cole@frostline.co.uk', role: 'manager', job_title: 'Installation Manager' },
  { key: 'gareth', name: 'Gareth Lloyd', email: 'gareth.lloyd@frostline.co.uk', role: 'sales', job_title: 'Senior Estimator' },
  { key: 'helen', name: 'Helen Price', email: 'helen.price@frostline.co.uk', role: 'sales', job_title: 'Account Manager' },
  { key: 'kev', name: 'Kevin Walsh', email: 'kevin.walsh@frostline.co.uk', role: 'stores', job_title: 'Procurement & Stores' },
] as const;

export const ENGINEERS = [
  { key: 'dave', name: 'Dave Whittaker', grade: 'senior', team: 'service', skills: ['ac', 'vrf', 'refrigeration', 'heat_pumps', 'commissioning'], postcode: 'BL9 9QT', lat: 53.5933, lng: -2.2966, van: 'FL21 KXD', colour: '#2563eb', quals: [['FGAS_CAT1', 900], ['IPAF', 400], ['CSCS', 700]] },
  { key: 'lee', name: 'Lee Ashworth', grade: 'engineer', team: 'service', skills: ['ac', 'refrigeration'], postcode: 'BL3 4PN', lat: 53.5625, lng: -2.4506, van: 'FL22 BHN', colour: '#0891b2', quals: [['FGAS_CAT1', 620], ['CSCS', 300]] },
  { key: 'sam', name: 'Sam Okafor', grade: 'engineer', team: 'service', skills: ['ac', 'vrf', 'controls'], postcode: 'SK4 2HJ', lat: 53.4235, lng: -2.1726, van: 'FL22 BHP', colour: '#7c3aed', quals: [['FGAS_CAT1', 1200], ['PASMA', 500], ['DBS', null]] },
  { key: 'craig', name: 'Craig Pennington', grade: 'senior', team: 'service', skills: ['heating', 'gas', 'ventilation', 'controls'], postcode: 'OL8 3LN', lat: 53.5271, lng: -2.1231, van: 'FL20 OPC', colour: '#dc2626', quals: [['GAS_SAFE_COMM', 260], ['BESA_VENT', 800], ['DBS', null], ['CSCS', 400]] },
  { key: 'jason', name: 'Jason Hughes', grade: 'engineer', team: 'service', skills: ['ac', 'heat_pumps'], postcode: 'WA2 8QA', lat: 53.4058, lng: -2.5795, van: 'FL23 WRT', colour: '#ea580c', quals: [['FGAS_CAT1', 25], ['CSCS', 600]] },
  { key: 'chloe', name: 'Chloe Marsden', grade: 'engineer', team: 'service', skills: ['ventilation', 'kitchen_extract', 'controls', 'heating'], postcode: 'M6 7FR', lat: 53.4935, lng: -2.3031, van: 'FL23 SLF', colour: '#db2777', quals: [['BESA_VENT', 700], ['DBS', null], ['ELEC_18TH', 900]] },
  { key: 'nathan', name: 'Nathan Byrne', grade: 'engineer', team: 'service', skills: ['refrigeration', 'ac'], postcode: 'L13 5XT', lat: 53.4136, lng: -2.9239, van: 'FL21 LVP', colour: '#16a34a', quals: [['FGAS_CAT1', 800], ['CSCS', -20]] },
  { key: 'imran', name: 'Imran Hussain', grade: 'senior', team: 'service', skills: ['ac', 'refrigeration', 'chillers', 'heat_pumps'], postcode: 'BD8 7DS', lat: 53.8003, lng: -1.7859, van: 'FL22 BDF', colour: '#ca8a04', quals: [['FGAS_CAT1', 450], ['IPAF', 150]] },
  { key: 'mike', name: 'Mike Brennan', grade: 'lead', team: 'installation', skills: ['vrf', 'ac', 'commissioning', 'heat_pumps'], postcode: 'OL11 4DS', lat: 53.6019, lng: -2.1719, van: 'FL20 RCH', colour: '#4f46e5', quals: [['FGAS_CAT1', 1000], ['IPAF', 300], ['SSSTS', 700], ['CSCS', 900]] },
  { key: 'ryan', name: 'Ryan Fletcher', grade: 'engineer', team: 'installation', skills: ['ac', 'ventilation'], postcode: 'WN3 5HB', lat: 53.5343, lng: -2.6509, van: 'FL23 WGN', colour: '#0d9488', quals: [['FGAS_CAT1', 1100], ['PASMA', 200], ['CSCS', 800]] },
  { key: 'josh', name: 'Josh Kelly', grade: 'apprentice', team: 'service', skills: ['ac'], postcode: 'M26 2TQ', lat: 53.5608, lng: -2.3264, van: null, colour: '#64748b', quals: [['CSCS', 500]] },
] as const;

export const SUBCONTRACTORS = [
  { key: 'paul', name: 'Paul Rigby', company: 'Rigby Gas Services Ltd', grade: 'senior', skills: ['heating', 'gas'], postcode: 'PR2 6HE', lat: 53.7743, lng: -2.7117, colour: '#78716c', quals: [['GAS_SAFE_COMM', 500]] },
] as const;

export const SUPPLIERS = [
  { key: 'nwrs', name: 'Northwest Refrigeration Supplies', account_no: 'FRO0142', phone: '0161 555 0142', email: 'trade@nwrefsupplies.example', categories: 'Refrigerant, compressors, refrigeration controls, copper', lead_days: 1 },
  { key: 'airsource', name: 'AirSource Distribution', account_no: 'FL-2231', phone: '0161 555 0199', email: 'orders@airsource.example', categories: 'AC units & spares (Daikin, Mitsubishi, Fujitsu), VRF, controllers', lead_days: 2 },
  { key: 'pennine', name: 'Pennine Heating Merchants', account_no: 'FROST01', phone: '01706 555 310', email: 'sales@penninehm.example', categories: 'Boiler spares, pumps, valves, flue', lead_days: 1 },
  { key: 'filterflow', name: 'FilterFlow Ltd', account_no: 'FF-8812', phone: '01204 555 877', email: 'orders@filterflow.example', categories: 'Panel & bag filters, belts, grease filters', lead_days: 3 },
  { key: 'arctic', name: 'Arctic Controls Wholesale', account_no: 'ACW-5520', phone: '0113 555 4410', email: 'trade@arcticcontrols.example', categories: 'Controls, sensors, contactors, electrical', lead_days: 2 },
] as const;

// sku, name, category, unit, cost, sell, supplier, depot [qty,min,max], van [qty,min,max] | null
export const PARTS: [string, string, string, string, number, number, string, [number, number, number], [number, number, number] | null][] = [
  ['REF-R410A-10', 'R410A refrigerant 10kg cylinder', 'Refrigerant', 'cylinder', 118, 165, 'nwrs', [6, 4, 10], [1, 1, 1]],
  ['REF-R32-9', 'R32 refrigerant 9kg cylinder', 'Refrigerant', 'cylinder', 96, 138, 'nwrs', [5, 3, 8], [1, 0, 1]],
  ['REF-R404A-10', 'R404A refrigerant 10.9kg cylinder', 'Refrigerant', 'cylinder', 310, 420, 'nwrs', [2, 2, 4], null],
  ['REF-R448A-10', 'R448A refrigerant 10kg cylinder', 'Refrigerant', 'cylinder', 265, 360, 'nwrs', [3, 2, 4], null],
  ['REF-N2-OF', 'Oxygen-free nitrogen cylinder refill', 'Refrigerant', 'each', 32, 55, 'nwrs', [4, 2, 6], null],
  ['CAP-RUN-35', 'Run capacitor 35µF 450V', 'Electrical', 'each', 6.4, 18.5, 'arctic', [22, 10, 30], [3, 2, 4]],
  ['CAP-RUN-45', 'Run capacitor 45µF 450V', 'Electrical', 'each', 7.1, 19.5, 'arctic', [15, 10, 30], [2, 2, 4]],
  ['CAP-START-UNI', 'Universal start capacitor kit', 'Electrical', 'each', 14.2, 34, 'arctic', [6, 4, 10], [1, 1, 2]],
  ['CON-3P-25A', 'Contactor 3-pole 25A 230V coil', 'Electrical', 'each', 24.5, 52, 'arctic', [8, 4, 12], [1, 1, 2]],
  ['THERM-10K', 'Thermistor sensor 10kΩ universal', 'Controls', 'each', 5.8, 21, 'arctic', [30, 15, 40], [4, 3, 6]],
  ['PUMP-COND-MINI', 'Aspen Mini Orange condensate pump', 'Condensate', 'each', 52, 96, 'airsource', [9, 6, 14], [2, 1, 2]],
  ['PUMP-COND-TANK', 'Condensate tank pump 2L (Silent+)', 'Condensate', 'each', 68, 118, 'airsource', [4, 3, 8], null],
  ['DRY-FD-164', 'Filter drier 164S 1/2" solder', 'Refrigeration', 'each', 13.5, 32, 'nwrs', [18, 10, 25], [3, 2, 4]],
  ['DRY-FD-083', 'Filter drier 083S 3/8" solder', 'Refrigeration', 'each', 9.8, 26, 'nwrs', [20, 10, 25], [3, 2, 4]],
  ['TXV-TES2', 'Danfoss TES2 thermostatic expansion valve', 'Refrigeration', 'each', 74, 138, 'nwrs', [3, 2, 5], null],
  ['SW-HP-AUTO', 'High pressure switch auto-reset', 'Refrigeration', 'each', 23, 49, 'nwrs', [7, 4, 10], [1, 1, 2]],
  ['SW-LP-AUTO', 'Low pressure switch auto-reset', 'Refrigeration', 'each', 23, 49, 'nwrs', [2, 4, 10], [1, 1, 2]],
  ['FAN-EVAP-10W', 'Evaporator fan motor 10W (cold room)', 'Refrigeration', 'each', 38, 79, 'nwrs', [6, 4, 8], [1, 0, 1]],
  ['HEAT-DOOR-CR', 'Cold room door heater cable 5m', 'Refrigeration', 'each', 29, 64, 'nwrs', [3, 2, 5], null],
  ['COMP-ZB26', 'Copeland ZB26KCE scroll compressor', 'Refrigeration', 'each', 845, 1240, 'nwrs', [0, 0, 1], null],
  ['CTRL-XR06', 'Dixell XR06CX refrigeration controller', 'Controls', 'each', 46, 98, 'arctic', [5, 3, 6], [1, 0, 1]],
  ['FAN-ODU-DK', 'Outdoor fan motor — Daikin RZQG 71-140', 'AC spares', 'each', 186, 312, 'airsource', [1, 1, 2], null],
  ['PCB-DK-FCQ', 'Indoor PCB — Daikin FCQG cassette', 'AC spares', 'each', 214, 358, 'airsource', [1, 1, 2], null],
  ['REM-DK-BRC1H', 'Daikin BRC1H wired remote controller', 'Controls', 'each', 88, 149, 'airsource', [4, 2, 6], null],
  ['REM-ME-PAR41', 'Mitsubishi PAR-41MAA wired controller', 'Controls', 'each', 92, 155, 'airsource', [3, 2, 6], null],
  ['FIL-G4-592', 'G4 panel filter 592×592×47', 'Filters', 'each', 5.2, 12.5, 'filterflow', [60, 40, 120], [6, 4, 8]],
  ['FIL-F7-BAG', 'F7 bag filter 592×592×600 (6 pocket)', 'Filters', 'each', 18.4, 38, 'filterflow', [24, 20, 60], null],
  ['FIL-GREASE-500', 'Baffle grease filter 500×500 stainless', 'Filters', 'each', 32, 64, 'filterflow', [8, 6, 16], null],
  ['FIL-CASSETTE', 'Cassette return air filter (universal cut)', 'Filters', 'each', 4.5, 14, 'filterflow', [30, 20, 50], [6, 4, 8]],
  ['BELT-SPA-1250', 'V-belt SPA 1250', 'Ventilation', 'each', 9.6, 22, 'filterflow', [10, 6, 16], [2, 1, 2]],
  ['BELT-SPZ-1000', 'V-belt SPZ 1000', 'Ventilation', 'each', 7.8, 19, 'filterflow', [3, 6, 16], [1, 1, 2]],
  ['BRG-6204', 'Bearing 6204-2RS', 'Ventilation', 'each', 6.2, 16, 'arctic', [12, 6, 20], [2, 1, 2]],
  ['GAS-VALVE-VK', 'Honeywell VK4105 gas valve', 'Heating', 'each', 132, 228, 'pennine', [1, 1, 2], null],
  ['IGN-ELEC-HAM', 'Ignition/flame probe electrode set — Hamworthy', 'Heating', 'each', 38, 74, 'pennine', [4, 2, 6], [1, 0, 1]],
  ['PUMP-GRUND-UPS', 'Grundfos UPS 32-80 circulating pump', 'Heating', 'each', 268, 412, 'pennine', [2, 1, 3], null],
  ['FLUE-GASKET', 'Boiler flue/burner gasket kit', 'Heating', 'each', 18, 39, 'pennine', [6, 4, 10], [1, 1, 2]],
  ['CU-38-15M', 'Copper pipe 3/8" coil 15m', 'Pipework', 'coil', 58, 92, 'nwrs', [8, 4, 12], [1, 1, 1]],
  ['CU-58-15M', 'Copper pipe 5/8" coil 15m', 'Pipework', 'coil', 96, 148, 'nwrs', [6, 4, 10], [1, 0, 1]],
  ['INS-13-38', 'Armaflex insulation 13mm × 3/8" (2m)', 'Pipework', 'length', 3.1, 7.5, 'nwrs', [80, 40, 120], [10, 6, 12]],
  ['TRUNK-80', 'PVC line-set trunking 80mm × 2m', 'Pipework', 'length', 8.2, 18, 'airsource', [30, 20, 60], [4, 2, 6]],
  ['BRK-WALL-550', 'Wall bracket 550mm (pair)', 'Installation', 'pair', 16, 34, 'airsource', [14, 8, 20], [1, 1, 2]],
  ['CHEM-COIL-5L', 'Coil cleaner (non-acid) 5L', 'Consumables', 'each', 14, 28, 'airsource', [12, 6, 16], [1, 1, 2]],
  ['CHEM-BIO-TAB', 'Condensate tray biocide tablets (50)', 'Consumables', 'tub', 11, 24, 'airsource', [9, 5, 12], [1, 1, 1]],
  ['LEAK-DET-SPRAY', 'Leak detection spray 400ml', 'Consumables', 'each', 5.5, 12, 'nwrs', [18, 10, 24], [2, 2, 3]],
  ['FUSE-KIT', 'Assorted fuses & terminal kit', 'Electrical', 'kit', 9, 20, 'arctic', [10, 5, 12], [1, 1, 1]],
];

export const CHECKLISTS = [
  {
    key: 'ac',
    name: 'AC / VRF service',
    items: [
      { key: 'isolate', label: 'Safe isolation and visual inspection', kind: 'check' },
      { key: 'filters', label: 'Filters cleaned / replaced', kind: 'check' },
      { key: 'coils', label: 'Indoor & outdoor coils cleaned', kind: 'check' },
      { key: 'condensate', label: 'Condensate tray, drain & pump tested', kind: 'check' },
      { key: 'electrical', label: 'Electrical connections checked / tightened', kind: 'check' },
      { key: 'leak', label: 'Refrigerant leak check (direct method)', kind: 'check' },
      { key: 'supply_temp', label: 'Supply air temperature', kind: 'reading', unit: '°C' },
      { key: 'return_temp', label: 'Return air temperature', kind: 'reading', unit: '°C' },
      { key: 'suction', label: 'Suction pressure', kind: 'reading', unit: 'bar' },
      { key: 'discharge', label: 'Discharge pressure', kind: 'reading', unit: 'bar' },
      { key: 'amps', label: 'Compressor running current', kind: 'reading', unit: 'A' },
      { key: 'controls', label: 'Controls / remote operation tested', kind: 'check' },
      { key: 'comments', label: 'Comments', kind: 'text' },
    ],
  },
  {
    key: 'refrig',
    name: 'Commercial refrigeration service',
    items: [
      { key: 'temps', label: 'Cabinet / room temperatures within range', kind: 'check' },
      { key: 'cabinet_temp', label: 'Product / air-off temperature', kind: 'reading', unit: '°C' },
      { key: 'condenser', label: 'Condenser cleaned', kind: 'check' },
      { key: 'evap', label: 'Evaporator & defrost operation checked', kind: 'check' },
      { key: 'door', label: 'Door seals, heaters and alarms tested', kind: 'check' },
      { key: 'leak', label: 'Refrigerant leak check', kind: 'check' },
      { key: 'sight', label: 'Sight glass clear / charge correct', kind: 'check' },
      { key: 'suction', label: 'Suction pressure', kind: 'reading', unit: 'bar' },
      { key: 'discharge', label: 'Discharge pressure', kind: 'reading', unit: 'bar' },
      { key: 'comments', label: 'Comments', kind: 'text' },
    ],
  },
  {
    key: 'ahu',
    name: 'AHU / ventilation service',
    items: [
      { key: 'filters', label: 'Filters replaced (record grade)', kind: 'check' },
      { key: 'dp', label: 'Filter differential pressure', kind: 'reading', unit: 'Pa' },
      { key: 'belts', label: 'Belts & pulleys checked / tensioned', kind: 'check' },
      { key: 'bearings', label: 'Bearings & motor condition', kind: 'check' },
      { key: 'dampers', label: 'Dampers and actuators operated', kind: 'check' },
      { key: 'coils', label: 'Heating / cooling coils inspected', kind: 'check' },
      { key: 'airflow', label: 'Supply airflow', kind: 'reading', unit: 'm³/s' },
      { key: 'comments', label: 'Comments', kind: 'text' },
    ],
  },
  {
    key: 'boiler',
    name: 'Commercial boiler service (gas)',
    items: [
      { key: 'visual', label: 'Visual inspection of appliance, flue and ventilation', kind: 'check' },
      { key: 'burner', label: 'Burner & electrodes cleaned / inspected', kind: 'check' },
      { key: 'gas_pressure', label: 'Burner gas pressure', kind: 'reading', unit: 'mbar' },
      { key: 'combustion', label: 'Combustion analysis CO/CO2 ratio', kind: 'reading', unit: 'ratio' },
      { key: 'safety', label: 'Safety devices & flame failure tested', kind: 'check' },
      { key: 'tightness', label: 'Gas tightness test', kind: 'check' },
      { key: 'pumps', label: 'Pumps / pressurisation unit checked', kind: 'check' },
      { key: 'comments', label: 'Comments', kind: 'text' },
    ],
  },
];

type SiteSeed = {
  key: string;
  name: string;
  address: string;
  town: string;
  county: string;
  postcode: string;
  lat: number;
  lng: number;
  building_type: string;
  opening_hours?: string;
  access_notes?: string;
  parking_notes?: string;
  hazards?: string;
  induction?: boolean;
  dbs?: boolean;
  permit?: boolean;
  ooh_access?: string;
  end_client?: string;
  contact?: [string, string, string, string]; // name, title, phone, email
  // tag suffix, category, manufacturer, model, location, install year, refrigerant, kg, capacity kW, condition
  assets: [string, string, string, string, string, number, string | null, number | null, number | null, string?][];
};

type CustomerSeed = {
  key: string;
  name: string;
  kind: 'end_client' | 'managing_agent' | 'fm_provider' | 'public_sector' | 'main_contractor';
  sector: string;
  status?: 'active' | 'prospect';
  phone: string;
  email: string;
  billing_address: string;
  billing_postcode: string;
  payment_terms_days?: number;
  po_required?: boolean;
  on_stop?: string;
  manager: string;
  notes?: string;
  contacts: [string, string, string, string, string[]][]; // name, title, phone, email, roles
  sites: SiteSeed[];
};

export const CUSTOMERS: CustomerSeed[] = [
  {
    key: 'pennine',
    name: 'Pennine Property Management Ltd',
    kind: 'managing_agent',
    sector: 'Offices & Commercial Property',
    phone: '0161 555 2200',
    email: 'facilities@pennineproperty.example',
    billing_address: '14 St Ann Street, Manchester',
    billing_postcode: 'M2 7LG',
    po_required: true,
    manager: 'helen',
    notes: 'Managing agent for several multi-let office buildings. Works orders issued via their FM helpdesk — always quote their WO number on invoices.',
    contacts: [
      ['Karen Oldfield', 'Head of Facilities', '0161 555 2201', 'karen.oldfield@pennineproperty.example', ['primary', 'decision_maker']],
      ['Accounts Payable', 'Accounts', '0161 555 2209', 'invoices@pennineproperty.example', ['accounts']],
    ],
    sites: [
      {
        key: 'harlow',
        name: 'Harlow House',
        address: '22 King Street',
        town: 'Manchester',
        county: 'Greater Manchester',
        postcode: 'M2 4WU',
        lat: 53.4811,
        lng: -2.2449,
        building_type: 'Multi-let office (8 floors)',
        opening_hours: 'Mon–Fri 07:00–19:00, security 24/7',
        access_notes: 'Sign in at reception. Plant room and roof keys from security desk (ask for Des). Roof access via 8th floor riser — permit required from building manager.',
        parking_notes: 'No on-site parking. NCP Kings Street West (receipts rechargeable).',
        hazards: 'Roof edge protection on east side only. Asbestos register held at reception (plant room ceiling tiles).',
        permit: true,
        ooh_access: 'Security on site 24/7 — 0161 555 2290',
        contact: ['Des Morley', 'Building Manager', '07700 900411', 'des.morley@pennineproperty.example'],
        assets: [
          ['VRF-01', 'VRF outdoor unit', 'Mitsubishi Electric', 'PUHY-P400YNW-A', 'Roof — north plant deck', 2017, 'R410A', 11.8, 45],
          ['VRF-02', 'VRF outdoor unit', 'Mitsubishi Electric', 'PUHY-P350YNW-A', 'Roof — north plant deck', 2017, 'R410A', 10.4, 40],
          ['FCU-3F-01', 'Cassette unit', 'Mitsubishi Electric', 'PLFY-P50VEM', '3rd floor meeting room 3.2', 2017, null, null, 5.6],
          ['FCU-3F-02', 'Cassette unit', 'Mitsubishi Electric', 'PLFY-P50VEM', '3rd floor open plan', 2017, null, null, 5.6],
          ['SPL-COMMS', 'Split AC', 'Daikin', 'FTXM35R / RXM35R', 'Ground floor comms room', 2021, 'R32', 0.95, 3.5],
          ['SPL-8F', 'Split AC', 'Daikin', 'FTXS50 / RXS50', '8th floor server room', 2009, 'R22', 1.9, 5, 'end_of_life'],
          ['AHU-01', 'Air handling unit', 'Swegon', 'GOLD RX 35', 'Roof plant room', 2017, null, null, null],
          ['BLR-01', 'Boiler', 'Hamworthy', 'Wessex ModuMax 254/220', 'Basement plant room', 2014, null, null, 220],
        ],
      },
      {
        key: 'quayview',
        name: 'Quay View Offices',
        address: 'Unit 3, Merchants Quay, Salford Quays',
        town: 'Salford',
        county: 'Greater Manchester',
        postcode: 'M50 3SG',
        lat: 53.4707,
        lng: -2.2952,
        building_type: 'Office (3 floors)',
        opening_hours: 'Mon–Fri 08:00–18:00',
        access_notes: 'Report to ground floor reception. Condensers in rear compound — padlock code 1974.',
        parking_notes: 'Visitor bays 1–4 at rear.',
        contact: ['Lucy Grant', 'Office Manager', '0161 555 8830', 'lucy.grant@quayviewtenant.example'],
        assets: [
          ['MS-01', 'Multi-split AC', 'Fujitsu', 'AOYG30LAT4', 'Rear compound', 2019, 'R410A', 2.4, 8],
          ['MS-02', 'Multi-split AC', 'Fujitsu', 'AOYG30LAT4', 'Rear compound', 2019, 'R410A', 2.4, 8],
          ['CAS-GF-01', 'Cassette unit', 'Fujitsu', 'AUXG18KVLA', 'Ground floor reception', 2019, null, null, 5.2],
          ['MVHR-01', 'Heat recovery unit (MVHR)', 'Nuaire', 'XBOXER XBC65', 'Ceiling void 2nd floor', 2019, null, null, null],
        ],
      },
      {
        key: 'kingsway',
        name: 'Kingsway Business Park — Unit 4',
        address: 'Unit 4, Kingsway Business Park, Rochdale',
        town: 'Rochdale',
        county: 'Greater Manchester',
        postcode: 'OL16 4NW',
        lat: 53.6003,
        lng: -2.1285,
        building_type: 'Office & light industrial',
        opening_hours: 'Mon–Fri 07:30–17:00',
        access_notes: 'Warehouse entrance side door. Hi-vis required in yard.',
        hazards: 'Forklift traffic in yard.',
        contact: ['Stuart Byrne', 'Site Supervisor', '07700 900622', 'stuart.byrne@kingswaytenant.example'],
        assets: [
          ['DUCT-01', 'Ducted unit', 'Toshiba', 'RAV-GM1101BTP-E', 'Office mezzanine', 2020, 'R32', 2.3, 10],
          ['HP-01', 'Air source heat pump', 'Mitsubishi Electric', 'Ecodan PUHZ-HW140YHA', 'Side yard', 2022, 'R410A', 4.0, 14],
          ['EXT-01', 'Extract fan', 'Systemair', 'KBR 355', 'Workshop roof', 2020, null, null, null],
        ],
      },
    ],
  },
  {
    key: 'brightwater',
    name: 'Brightwater Care Group',
    kind: 'end_client',
    sector: 'Healthcare & Care',
    phone: '01204 555 700',
    email: 'estates@brightwatercare.example',
    billing_address: 'Brightwater House, 2 Chorley New Road, Bolton',
    billing_postcode: 'BL1 4AP',
    payment_terms_days: 30,
    manager: 'helen',
    notes: 'Three residential care homes. Heating & hot water failures are always treated as emergencies (vulnerable residents). DBS-checked engineers only.',
    contacts: [
      ['Graham Toole', 'Estates Manager', '07700 900155', 'graham.toole@brightwatercare.example', ['primary', 'decision_maker', 'out_of_hours']],
      ['Brightwater Finance', 'Purchase Ledger', '01204 555 709', 'finance@brightwatercare.example', ['accounts']],
    ],
    sites: [
      {
        key: 'oakfield',
        name: 'Oakfield Lodge Care Home',
        address: '41 Markland Hill Lane',
        town: 'Bolton',
        county: 'Greater Manchester',
        postcode: 'BL1 5EZ',
        lat: 53.5892,
        lng: -2.4721,
        building_type: 'Residential care home (48 beds)',
        opening_hours: '24/7 — avoid mealtimes 12:00–13:30 in dining areas',
        access_notes: 'Sign in with nurse in charge. Wear visitor lanyard at all times. Boiler house key in manager office.',
        parking_notes: 'Staff car park — do not block ambulance bay.',
        hazards: 'Vulnerable residents — never leave tools/ladders unattended. Infection control: hand gel on entry.',
        dbs: true,
        ooh_access: 'Nurse in charge 24/7 — 01204 555 711',
        contact: ['Angela Firth', 'Home Manager', '01204 555 710', 'angela.firth@brightwatercare.example'],
        assets: [
          ['BLR-01', 'Boiler', 'Remeha', 'Quinta Pro 115', 'Boiler house', 2016, null, null, 115],
          ['BLR-02', 'Boiler', 'Remeha', 'Quinta Pro 115', 'Boiler house', 2016, null, null, 115],
          ['CWH-01', 'Water heater', 'Andrews', 'MAXXflo EVO 45/251', 'Boiler house', 2018, null, null, 45],
          ['SPL-MED', 'Split AC', 'Mitsubishi Electric', 'MSZ-LN35VG', 'Medication room', 2021, 'R32', 1.0, 3.5],
          ['EXT-KIT', 'Kitchen extract canopy', 'Halton', 'KVE canopy + fan', 'Main kitchen', 2016, null, null, null],
          ['MVHR-EAST', 'Heat recovery unit (MVHR)', 'Vent-Axia', 'Sentinel Kinetic Advance', 'East wing loft', 2016, null, null, null],
        ],
      },
      {
        key: 'meadowbank',
        name: 'Meadowbank House',
        address: '7 Upper Dicconson Street',
        town: 'Wigan',
        county: 'Greater Manchester',
        postcode: 'WN1 2AD',
        lat: 53.5498,
        lng: -2.6386,
        building_type: 'Residential care home (32 beds)',
        opening_hours: '24/7',
        access_notes: 'Keypad entry — code from Home Manager. Plant room at rear via garden gate.',
        hazards: 'Dementia unit on first floor — keep doors closed.',
        dbs: true,
        ooh_access: 'Senior carer on duty — 01942 555 320',
        contact: ['Paula Nixon', 'Home Manager', '01942 555 321', 'paula.nixon@brightwatercare.example'],
        assets: [
          ['BLR-01', 'Boiler', 'Ideal', 'Evomax 2 80', 'Rear plant room', 2019, null, null, 80],
          ['BLR-02', 'Boiler', 'Ideal', 'Evomax 2 80', 'Rear plant room', 2019, null, null, 80],
          ['SPL-LOUNGE', 'Split AC', 'Daikin', 'FTXM50R', 'Garden lounge', 2023, 'R32', 1.3, 5],
        ],
      },
      {
        key: 'willows',
        name: 'The Willows',
        address: '118 Bramhall Lane',
        town: 'Stockport',
        county: 'Greater Manchester',
        postcode: 'SK2 6JA',
        lat: 53.3981,
        lng: -2.1553,
        building_type: 'Residential & nursing home (40 beds)',
        opening_hours: '24/7',
        access_notes: 'Report to reception. Roof plant via internal stair — escort required.',
        dbs: true,
        contact: ['Dr. Sunil Mehta', 'Registered Manager', '0161 555 4470', 'sunil.mehta@brightwatercare.example'],
        assets: [
          ['BLR-01', 'Boiler', 'Hamworthy', 'Varmax 120', 'Roof plant room', 2015, null, null, 120],
          ['AHU-01', 'Air handling unit', 'Nuaire', 'XBOXER XBC85', 'Roof', 2015, null, null, null],
          ['CR-KIT', 'Cold room', 'Foster', 'Modular cold room 2.4×1.8 + condensing unit', 'Kitchen stores', 2018, 'R404A', 3.4, 2.1],
        ],
      },
    ],
  },
  {
    key: 'nff',
    name: 'Northern Fresh Foods Ltd',
    kind: 'end_client',
    sector: 'Retail',
    phone: '0161 555 9100',
    email: 'maintenance@northernfresh.example',
    billing_address: 'Northern Fresh Foods, Moss Lane Industrial Estate, Whitefield',
    billing_postcode: 'M45 8FJ',
    manager: 'helen',
    notes: 'Regional convenience food retailer. Refrigeration failures = stock loss; P1 if product temperatures rising. Stores prefer work before 10:00 or after 20:00.',
    contacts: [
      ['Sarah Whitehead', 'Maintenance Manager', '07700 900781', 'sarah.whitehead@northernfresh.example', ['primary', 'decision_maker', 'out_of_hours']],
      ['NFF Accounts', 'Accounts', '0161 555 9105', 'accounts@northernfresh.example', ['accounts']],
    ],
    sites: [
      {
        key: 'nff-bury',
        name: 'Northern Fresh — Bury Market Street',
        address: '58 Market Street',
        town: 'Bury',
        county: 'Greater Manchester',
        postcode: 'BL9 0BH',
        lat: 53.5926,
        lng: -2.2966,
        building_type: 'Convenience store',
        opening_hours: '07:00–22:00 daily',
        access_notes: 'Rear service door on Spring Street. Condensing units in rear yard cage (key with store manager).',
        contact: ['Store Manager (Bury)', 'Store Manager', '0161 555 9121', 'bury@northernfresh.example'],
        assets: [
          ['RD-01', 'Refrigerated display', 'Carrier', 'Multideck MD 3.75m', 'Shop floor — dairy', 2020, null, null, null],
          ['RD-02', 'Refrigerated display', 'Carrier', 'Multideck MD 2.5m', 'Shop floor — produce', 2020, null, null, null],
          ['CU-01', 'Condensing unit', 'Emerson', 'Copeland EazyCool ZXLE', 'Rear yard cage', 2020, 'R448A', 8.2, 6.5],
          ['CR-01', 'Cold room', 'Foster', 'Modular chiller room', 'Rear stores', 2020, 'R448A', 2.5, 2.4],
          ['SPL-01', 'Split AC', 'Mitsubishi Electric', 'PKA-M60KAL', 'Shop floor', 2020, 'R32', 1.6, 6],
        ],
      },
      {
        key: 'nff-prestwich',
        name: 'Northern Fresh — Prestwich Village',
        address: '3 Longfield Centre',
        town: 'Prestwich',
        county: 'Greater Manchester',
        postcode: 'M25 1AY',
        lat: 53.5335,
        lng: -2.2853,
        building_type: 'Convenience store',
        opening_hours: '07:00–22:00 daily',
        access_notes: 'Deliveries entrance off Fairfax Road. Plant on flat roof — fixed ladder.',
        hazards: 'Roof hatch — no edge protection near hatch, harness point provided.',
        contact: ['Store Manager (Prestwich)', 'Store Manager', '0161 555 9131', 'prestwich@northernfresh.example'],
        assets: [
          ['RD-01', 'Refrigerated display', 'Carrier', 'Multideck MD 3.75m', 'Shop floor — chilled', 2016, null, null, null],
          ['FZ-01', 'Refrigerated display', 'Carrier', 'Glass door freezer 3-door', 'Shop floor — frozen', 2016, null, null, null],
          ['CU-01', 'Condensing unit', 'Tecumseh', 'Silensys TAGD4546ZHR', 'Roof', 2016, 'R404A', 9.5, 5.8],
          ['CU-02', 'Condensing unit', 'Tecumseh', 'Silensys TFH4540ZHR (LT)', 'Roof', 2016, 'R404A', 6.8, 3.2],
        ],
      },
      {
        key: 'nff-radcliffe',
        name: 'Northern Fresh — Radcliffe',
        address: '112 Blackburn Street',
        town: 'Radcliffe',
        county: 'Greater Manchester',
        postcode: 'M26 2JW',
        lat: 53.5617,
        lng: -2.3268,
        building_type: 'Convenience store',
        opening_hours: '07:00–22:00 daily',
        access_notes: 'Rear yard via Church Street gate.',
        contact: ['Store Manager (Radcliffe)', 'Store Manager', '0161 555 9141', 'radcliffe@northernfresh.example'],
        assets: [
          ['RD-01', 'Refrigerated display', 'Carrier', 'Multideck MD 3.75m', 'Shop floor', 2023, null, null, null],
          ['CU-01', 'Condensing unit', 'Emerson', 'Copeland CO2 EazyCool', 'Rear yard', 2023, 'R744', 6.0, 7.0],
        ],
      },
    ],
  },
  {
    key: 'staidans',
    name: "St Aidan's Academy Trust",
    kind: 'public_sector',
    sector: 'Education',
    phone: '01204 555 360',
    email: 'estates@staidanstrust.example',
    billing_address: "St Aidan's Academy Trust, Tonge Moor Road, Bolton",
    billing_postcode: 'BL2 2LJ',
    po_required: true,
    manager: 'helen',
    notes: 'PPM contract only — reactive work chargeable against a PO. Major works scheduled in school holidays. All engineers must have DBS and sign in at school office.',
    contacts: [
      ['Mark Heywood', 'Trust Estates Lead', '07700 900233', 'm.heywood@staidanstrust.example', ['primary', 'decision_maker']],
      ['Trust Finance', 'Finance Officer', '01204 555 369', 'finance@staidanstrust.example', ['accounts']],
    ],
    sites: [
      {
        key: 'hollins',
        name: 'Hollins Park Primary School',
        address: 'Hollins Lane',
        town: 'Bury',
        county: 'Greater Manchester',
        postcode: 'BL9 8AT',
        lat: 53.5695,
        lng: -2.2698,
        building_type: 'Primary school',
        opening_hours: 'Term time 07:30–17:30. Holidays by arrangement with caretaker.',
        access_notes: 'Sign in at school office; DBS badge must be visible. Caretaker: Brian (07700 900345).',
        hazards: 'Children present — no work in corridors during break times.',
        dbs: true,
        contact: ['Brian Tatlock', 'Site Manager / Caretaker', '07700 900345', 'site@hollinspark.example'],
        assets: [
          ['BLR-01', 'Boiler', 'Ideal', 'Imax Xtra EL 160', 'Boiler room', 2012, null, null, 160],
          ['SPL-ICT', 'Split AC', 'Fujitsu', 'ASYG12KGTF', 'ICT suite', 2018, 'R32', 0.8, 3.5],
          ['EXT-KIT', 'Kitchen extract canopy', 'Vent-Axia', 'Canopy + ACP 400 fan', 'School kitchen', 2012, null, null, null],
        ],
      },
      {
        key: 'staidans-high',
        name: "St Aidan's High School",
        address: 'Tonge Moor Road',
        town: 'Bolton',
        county: 'Greater Manchester',
        postcode: 'BL2 2LJ',
        lat: 53.5905,
        lng: -2.4119,
        building_type: 'Secondary school (1,100 pupils)',
        opening_hours: 'Term time 07:00–18:00',
        access_notes: 'Contractor entrance Gate B. Sign in at facilities office.',
        dbs: true,
        contact: ['Janet Crompton', 'Facilities Manager', '01204 555 380', 'j.crompton@staidanshigh.example'],
        assets: [
          ['AHU-SH', 'Air handling unit', 'Swegon', 'GOLD RX 50', 'Sports hall plant room', 2019, null, null, null],
          ['VRF-01', 'VRF outdoor unit', 'Daikin', 'RXYQ16U', 'Science block roof', 2019, 'R410A', 11.8, 45],
          ['CAS-LAB1', 'Cassette unit', 'Daikin', 'FXZQ32A', 'Science lab 1', 2019, null, null, 3.6],
          ['CAS-LAB2', 'Cassette unit', 'Daikin', 'FXZQ32A', 'Science lab 2', 2019, null, null, 3.6],
          ['SPL-SRV', 'Split AC', 'Daikin', 'FTXM60R', 'Server room', 2019, 'R32', 1.5, 6],
          ['BLR-01', 'Boiler', 'Hamworthy', 'Purewell VariHeat 180', 'Main plant room', 2011, null, null, 180, 'poor'],
        ],
      },
    ],
  },
  {
    key: 'deansgate',
    name: 'Deansgate Hotel Group Ltd',
    kind: 'end_client',
    sector: 'Hospitality & Leisure',
    phone: '0161 555 6000',
    email: 'engineering@deansgatehotel.example',
    billing_address: '301 Deansgate, Manchester',
    billing_postcode: 'M3 4LQ',
    manager: 'helen',
    notes: '140-room city centre hotel. Guest-facing work must be arranged with duty manager. Kitchen extract failures stop food service — P1.',
    contacts: [['Marco Rossi', 'Chief Engineer', '07700 900818', 'marco.rossi@deansgatehotel.example', ['primary', 'decision_maker', 'out_of_hours']]],
    sites: [
      {
        key: 'deansgate-hotel',
        name: 'The Deansgate Hotel',
        address: '301 Deansgate',
        town: 'Manchester',
        county: 'Greater Manchester',
        postcode: 'M3 4LQ',
        lat: 53.4744,
        lng: -2.2508,
        building_type: 'Hotel (140 rooms, restaurant, conference)',
        opening_hours: '24/7',
        access_notes: 'Staff entrance on Great Bridgewater Street. Report to engineering office B1. Room works via duty manager only.',
        parking_notes: 'Loading bay 30 mins max.',
        hazards: 'Kitchen — hot surfaces, slippery floors. Rooftop plant fenced.',
        induction: true,
        ooh_access: 'Duty manager 24/7 — 0161 555 6001',
        contact: ['Marco Rossi', 'Chief Engineer', '07700 900818', 'marco.rossi@deansgatehotel.example'],
        assets: [
          ['CH-01', 'Chiller', 'Carrier', 'AquaSnap 30RBP 160', 'Roof plant', 2015, 'R410A', 28, 160],
          ['AHU-01', 'Air handling unit', 'Systemair', 'Topvex SX 20', 'Roof plant', 2015, null, null, null],
          ['AHU-02', 'Air handling unit', 'Systemair', 'Topvex SX 12 (conference)', 'Roof plant', 2015, null, null, null],
          ['EXT-KIT', 'Kitchen extract canopy', 'Halton', 'KVI capture jet + fan', 'Main kitchen', 2015, null, null, null],
          ['CR-01', 'Cold room', 'Williams', 'Modular chiller room', 'Kitchen stores', 2019, 'R449A', 4.5, 3],
          ['CR-02', 'Cold room', 'Williams', 'Modular freezer room', 'Kitchen stores', 2019, 'R449A', 5.2, 2.6],
          ['BLR-01', 'Boiler', 'Hamworthy', 'Wessex ModuMax 360', 'Basement plant', 2015, null, null, 360],
        ],
      },
    ],
  },
  {
    key: 'calderbrook',
    name: 'Calderbrook Engineering Ltd',
    kind: 'end_client',
    sector: 'Light Industrial & Warehousing',
    phone: '01422 555 240',
    email: 'ops@calderbrook.example',
    billing_address: 'Calderbrook Works, Wakefield Road, Halifax',
    billing_postcode: 'HX3 8AE',
    manager: 'helen',
    notes: 'Acquired from Calder Cooling Services (2021). Precision machining — process cooling chiller is critical.',
    contacts: [['Neil Sutcliffe', 'Operations Director', '01422 555 241', 'neil.sutcliffe@calderbrook.example', ['primary', 'decision_maker']]],
    sites: [
      {
        key: 'calderbrook-works',
        name: 'Calderbrook Works',
        address: 'Wakefield Road',
        town: 'Halifax',
        county: 'West Yorkshire',
        postcode: 'HX3 8AE',
        lat: 53.7132,
        lng: -1.8456,
        building_type: 'Light industrial / machine shop',
        opening_hours: 'Mon–Fri 06:00–22:00 (two shifts)',
        access_notes: 'Gatehouse sign-in. Site induction video (15 min) on first visit. Steel toe caps & glasses mandatory.',
        hazards: 'Moving machinery, overhead crane in bay 2.',
        induction: true,
        contact: ['Neil Sutcliffe', 'Operations Director', '01422 555 241', 'neil.sutcliffe@calderbrook.example'],
        assets: [
          ['PCH-01', 'Chiller', 'Daikin Applied', 'EWAT-B 085', 'Yard — process cooling', 2018, 'R134a', 16, 85],
          ['SPL-OFF1', 'Split AC', 'LG', 'S12ET / UL', 'Offices', 2013, 'R410A', 1.0, 3.5],
          ['SPL-QA', 'Split AC', 'LG', 'PC12SQ', 'QA lab', 2021, 'R32', 0.9, 3.5],
          ['HTR-01', 'Other', 'Powrmatic', 'NVx gas warm air heater', 'Bay 1', 2012, null, null, 60],
        ],
      },
    ],
  },
  {
    key: 'mersey',
    name: 'Mersey Logistics Ltd',
    kind: 'end_client',
    sector: 'Light Industrial & Warehousing',
    phone: '0151 555 3300',
    email: 'facilities@merseylogistics.example',
    billing_address: 'Unit 12, Knowsley Business Park, Liverpool',
    billing_postcode: 'L33 7TX',
    manager: 'gareth',
    notes: 'No maintenance contract — ad hoc reactive work. Proposal for PPM contract sent (see quotes).',
    contacts: [['Joanne Kerr', 'Facilities Coordinator', '0151 555 3310', 'joanne.kerr@merseylogistics.example', ['primary']]],
    sites: [
      {
        key: 'knowsley',
        name: 'Knowsley Distribution Centre',
        address: 'Unit 12, Knowsley Business Park',
        town: 'Liverpool',
        county: 'Merseyside',
        postcode: 'L33 7TX',
        lat: 53.4907,
        lng: -2.8472,
        building_type: 'Distribution warehouse + offices',
        opening_hours: '24/7 operations; offices Mon–Fri 08:00–17:00',
        access_notes: 'Gatehouse — hi-vis mandatory. Escort in warehouse.',
        hazards: 'HGV & forklift movements.',
        contact: ['Joanne Kerr', 'Facilities Coordinator', '0151 555 3310', 'joanne.kerr@merseylogistics.example'],
        assets: [
          ['VRF-OFF', 'VRF outdoor unit', 'LG', 'Multi V 5 ARUM140LTE5', 'Office roof', 2016, 'R410A', 9.0, 40],
          ['SPL-SEC', 'Split AC', 'Samsung', 'AR12TXFCAWKNEU', 'Gatehouse', 2020, 'R32', 0.9, 3.5],
          ['CR-01', 'Cold room', 'Foster', 'Chilled goods hold 6×4m', 'Warehouse bay 3', 2016, 'R404A', 18, 8],
        ],
      },
    ],
  },
  {
    key: 'vantage',
    name: 'Vantage Gyms Ltd',
    kind: 'end_client',
    sector: 'Hospitality & Leisure',
    phone: '0161 555 7710',
    email: 'ops@vantagegyms.example',
    billing_address: '8 Wellington Road South, Stockport',
    billing_postcode: 'SK1 3UA',
    on_stop: 'Invoices over 90 days (£3,420 outstanding) — credit control hold 01/09',
    manager: 'gareth',
    contacts: [['Dean Mullins', 'Operations Manager', '07700 900912', 'dean.mullins@vantagegyms.example', ['primary', 'decision_maker']]],
    sites: [
      {
        key: 'vantage-stockport',
        name: 'Vantage Gym Stockport',
        address: '8 Wellington Road South',
        town: 'Stockport',
        county: 'Greater Manchester',
        postcode: 'SK1 3UA',
        lat: 53.4088,
        lng: -2.1576,
        building_type: 'Gym / leisure',
        opening_hours: '06:00–22:00',
        assets: [
          ['DUCT-01', 'Ducted unit', 'Daikin', 'FBA140A / RZAG140', 'Main gym floor', 2019, 'R32', 3.4, 14],
          ['AHU-01', 'Air handling unit', 'Nuaire', 'XBOXER XBC55', 'Roof', 2019, null, null, null],
        ],
      },
      {
        key: 'vantage-oldham',
        name: 'Vantage Gym Oldham',
        address: 'Unit 2, Spindles Retail Park',
        town: 'Oldham',
        county: 'Greater Manchester',
        postcode: 'OL1 1HD',
        lat: 53.5412,
        lng: -2.1146,
        building_type: 'Gym / leisure',
        opening_hours: '06:00–22:00',
        assets: [['DUCT-01', 'Ducted unit', 'Daikin', 'FBA125A / RZAG125', 'Main gym floor', 2020, 'R32', 3.0, 12.5]],
      },
    ],
  },
  {
    key: 'kestrel',
    name: 'Kestrel FM Services Ltd',
    kind: 'fm_provider',
    sector: 'Multi-Site & Facilities Management',
    phone: '01772 555 400',
    email: 'helpdesk@kestrelfm.example',
    billing_address: 'Kestrel House, Preston Business Centre, Preston',
    billing_postcode: 'PR2 9ZB',
    po_required: true,
    payment_terms_days: 45,
    manager: 'helen',
    notes: 'FM provider — we are their HVAC subcontractor for Lancashire Retail Parks. Every job needs a Kestrel work order (WO-xxxxx) before attendance except P1. Upload job sheets to their portal within 48h.',
    contacts: [
      ['Kestrel Helpdesk', 'FM Helpdesk', '01772 555 401', 'helpdesk@kestrelfm.example', ['primary']],
      ['Owen Clarke', 'Contract Manager', '07700 900533', 'owen.clarke@kestrelfm.example', ['decision_maker']],
    ],
    sites: [
      {
        key: 'deepdale',
        name: 'Deepdale Retail Park — Units 5–7',
        address: 'Blackpool Road',
        town: 'Preston',
        county: 'Lancashire',
        postcode: 'PR1 6QY',
        lat: 53.7729,
        lng: -2.6868,
        building_type: 'Retail park units',
        end_client: 'lrp',
        opening_hours: 'Mon–Sat 09:00–20:00, Sun 10:30–16:30',
        access_notes: 'Contact centre management office (Unit 1) for roof access key and permit.',
        permit: true,
        contact: ['Centre Management Office', 'Centre Manager', '01772 555 450', 'deepdale@lrp.example'],
        assets: [
          ['VRF-U5', 'VRF outdoor unit', 'Toshiba', 'SMMS-u MMY-UP2241', 'Roof above Unit 5', 2018, 'R410A', 14.5, 22.4],
          ['VRF-U7', 'VRF outdoor unit', 'Toshiba', 'SMMS-u MMY-UP1801', 'Roof above Unit 7', 2018, 'R410A', 12.0, 18],
          ['AC-MALL', 'Ducted unit', 'Toshiba', 'RAV-GM1401ATP', 'Mall walkway', 2018, 'R32', 3.1, 12.5],
        ],
      },
      {
        key: 'whitebirk',
        name: 'Whitebirk Retail Park — Unit 2',
        address: 'Whitebirk Drive',
        town: 'Blackburn',
        county: 'Lancashire',
        postcode: 'BB1 3HT',
        lat: 53.7564,
        lng: -2.4491,
        building_type: 'Retail unit',
        end_client: 'lrp',
        opening_hours: 'Mon–Sat 09:00–20:00',
        contact: ['Unit 2 Store Manager', 'Store Manager', '01254 555 620', 'whitebirk2@lrp.example'],
        assets: [
          ['CAS-01', 'Cassette unit', 'Samsung', 'AC100RN4DKG', 'Sales floor front', 2021, 'R32', 2.2, 10],
          ['CAS-02', 'Cassette unit', 'Samsung', 'AC100RN4DKG', 'Sales floor rear', 2021, 'R32', 2.2, 10],
        ],
      },
    ],
  },
  {
    key: 'lrp',
    name: 'Lancashire Retail Parks plc',
    kind: 'end_client',
    sector: 'Retail',
    phone: '01772 555 450',
    email: 'estates@lrp.example',
    billing_address: 'LRP, Fishergate, Preston',
    billing_postcode: 'PR1 2NJ',
    manager: 'helen',
    notes: 'End client — work is instructed and paid via Kestrel FM. Do not invoice LRP directly.',
    contacts: [['Rebecca Hall', 'Estates Surveyor', '01772 555 452', 'rebecca.hall@lrp.example', ['decision_maker']]],
    sites: [],
  },
  {
    key: 'ribble',
    name: 'Ribble Valley Brewing Co.',
    kind: 'end_client',
    sector: 'Hospitality & Leisure',
    phone: '01200 555 180',
    email: 'hello@ribblebrewing.example',
    billing_address: 'Holden Mill, Waddington Road, Clitheroe',
    billing_postcode: 'BB7 2HE',
    manager: 'gareth',
    contacts: [['Tom Cawthorne', 'Head Brewer & Director', '07700 900188', 'tom@ribblebrewing.example', ['primary', 'decision_maker']]],
    sites: [
      {
        key: 'holden-mill',
        name: 'Holden Mill Brewery & Taproom',
        address: 'Waddington Road',
        town: 'Clitheroe',
        county: 'Lancashire',
        postcode: 'BB7 2HE',
        lat: 53.8783,
        lng: -2.3969,
        building_type: 'Brewery, cold store & taproom',
        opening_hours: 'Brewery Mon–Fri 07:00–16:00; taproom Thu–Sun',
        access_notes: 'Brewery door at rear yard. Cellar via taproom.',
        hazards: 'CO2 in cellar & fermentation room — check alarm status before entry. Wet floors.',
        contact: ['Tom Cawthorne', 'Head Brewer', '07700 900188', 'tom@ribblebrewing.example'],
        assets: [
          ['GLY-01', 'Chiller', 'ICS Cool Energy', 'Glycol chiller GC-30', 'Brewhouse yard', 2019, 'R407C', 7.5, 30],
          ['CR-01', 'Cold room', 'Foster', 'Beer cold store 4×3m', 'Warehouse', 2019, 'R449A', 6.0, 4.5],
          ['CEL-01', 'Condensing unit', 'IMI', 'Cellar cooler 1.8kW', 'Taproom cellar', 2014, 'R404A', 1.8, 1.8],
        ],
      },
    ],
  },
  {
    key: 'cheshiredental',
    name: 'Cheshire Dental Partners',
    kind: 'end_client',
    sector: 'Healthcare & Care',
    phone: '01565 555 290',
    email: 'practice@cheshiredental.example',
    billing_address: '9 Princess Street, Knutsford',
    billing_postcode: 'WA16 6DD',
    manager: 'gareth',
    contacts: [['Dr. Emma Lawson', 'Practice Principal', '01565 555 291', 'emma.lawson@cheshiredental.example', ['primary', 'decision_maker']]],
    sites: [
      {
        key: 'knutsford-dental',
        name: 'Knutsford Dental Practice',
        address: '9 Princess Street',
        town: 'Knutsford',
        county: 'Cheshire',
        postcode: 'WA16 6DD',
        lat: 53.3037,
        lng: -2.3727,
        building_type: 'Dental practice',
        opening_hours: 'Mon–Fri 08:30–17:30',
        access_notes: 'Work in surgeries only before 08:30 or after 17:30.',
        assets: [
          ['SPL-S1', 'Split AC', 'Mitsubishi Electric', 'MSZ-AP25VG', 'Surgery 1', 2017, 'R32', 0.7, 2.5],
          ['SPL-S2', 'Split AC', 'Mitsubishi Electric', 'MSZ-AP25VG', 'Surgery 2', 2017, 'R32', 0.7, 2.5],
          ['SPL-DECON', 'Split AC', 'Mitsubishi Electric', 'MSZ-AP35VG', 'Decontamination room', 2017, 'R32', 0.9, 3.5],
        ],
      },
    ],
  },
  {
    key: 'salfordhub',
    name: 'Salford Innovation Hub CIC',
    kind: 'end_client',
    sector: 'Offices & Commercial Property',
    status: 'prospect',
    phone: '0161 555 8400',
    email: 'building@salfordhub.example',
    billing_address: 'Chapel Street, Salford',
    billing_postcode: 'M3 7AJ',
    manager: 'gareth',
    notes: 'Refurbishing former mill into co-working space. Enquiry via website for heating & cooling. Survey completed; VRF heat recovery proposal issued.',
    contacts: [['Aisha Rahman', 'Development Manager', '07700 900677', 'aisha.rahman@salfordhub.example', ['primary', 'decision_maker']]],
    sites: [
      {
        key: 'chapel-mill',
        name: 'Chapel Street Mill',
        address: '210 Chapel Street',
        town: 'Salford',
        county: 'Greater Manchester',
        postcode: 'M3 7AJ',
        lat: 53.4862,
        lng: -2.2588,
        building_type: 'Mill conversion — co-working (4 floors)',
        access_notes: 'Construction site — main contractor sign-in and CSCS required.',
        hazards: 'Live construction site.',
        induction: true,
        assets: [],
      },
    ],
  },
];
